# -*- coding: utf-8 -*-
"""PRODIGY_GA_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HcuQDODw7JGY-RLfoRLYOqsOtNbcgnRj
"""

# PRODIGY_GA_02 - Image Generation
# Ready for GitHub upload

print("🎨 AI Image Generation Project")
print("="*50)

# Install
!pip install -q diffusers transformers

print("✅ Setup complete!")

# Simple test
from diffusers import StableDiffusionPipeline
import torch

pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5")
if torch.cuda.is_available():
    pipe = pipe.to("cuda")

print("✅ Model loaded!")

# Test function
def generate(prompt):
    print(f"\nGenerating: {prompt}")
    image = pipe(prompt).images[0]
    image.save("output.png")
    print("✅ Image saved as output.png")
    return image

# Quick test
img = generate("A beautiful sunset")
print("\n🎉 Project working!")

# GitHub instructions
print("\n" + "="*50)
print("📤 TO SAVE TO GITHUB:")
print("1. File → Save a copy in GitHub")
print("2. Repository: PRODIGY_GA_02")
print("3. Public ✓")
print("4. Click OK")
print("="*50)